apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: kyverno-policies
spec:
  project: security
  source:
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: "v2.5.5"
    chart: kyverno-policies
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  ignoreDifferences:
  - group: "kyverno.io"
    kind: "ClusterPolicy"
    jsonPointers:
    - /spec/rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
