apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: bluegreen
spec:
  project: examples
  source:
    repoURL: https://github.com/luismiguelsaez/helm-charts
    targetRevision: main
    path: argocd-bluegreen
    directory: {}
    helm:
      values: |-
        image:
          tag: 1.20.1-alpine
        ingress:
          enabled: true
          className: nginx
          annotations: {}
          hosts:
            - host: bluegreen.minikube.cloud
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: examples
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
