apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: cluster-autoscaler
spec:
    helm:
      values: |-
        cloudProvider: aws
        dnsPolicy: Default
        autoDiscovery:
          clusterName: "k8s-test"
          tags:
            - k8s.io/cluster-autoscaler/enabled
            - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
          roles:
            - worker
        rbac:
          create: true
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::484308071187:role/cluster-autoscaler@kube-system
            automountServiceAccountToken: true
        awsRegion: eu-central-1
        extraArgs:
          logtostderr: true
          stderrthreshold: info
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
