apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: filebeat
spec:
  project: monitoring
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: filebeat
    helm:
      values: |-
        daemonset:
          enabled: true
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "1000m"
              memory: "200Mi"
          filebeatConfig:
            filebeat.yml: |
              filebeat.inputs:
              - type: container
                paths:
                  - /var/log/containers/*.log
                processors:
                - add_host_metadata: ~
                - add_kubernetes_metadata:
                    host: ${NODE_NAME}
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"
              output.logstash:
                enabled: false
                hosts: ["graylog-tcp-input-private.lokalise.cloud:5044"]
                ssl:
                  enabled: true
              output.console:
                enabled: true
                pretty: true
              logging:
                level: warning
