apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/aws-load-balancer-controller
- ../../infra/apps/external-dns
patchesStrategicMerge:
- aws-load-balancer-controller.yaml
- external-dns.yaml
