apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/aws-load-balancer-controller
- ../../infra/apps/external-dns
- ../../infra/apps/cluster-autoscaler
- ../../infra/apps/metrics-server
- ../../infra/apps/filebeat
- ../../infra/apps/nginx-ingress
patchesStrategicMerge:
- aws-load-balancer-controller.yaml
- external-dns.yaml
- cluster-autoscaler.yaml
- metrics-server.yaml
- filebeat.yaml
- nginx-ingress.yaml
