apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: metrics-server
spec:
  source:
    helm:
      values: |-
        nameOverride: "metrics-server"
        fullnameOverride: "metrics-server"
        notifications:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
