apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-prometheus-crds
  - kube-prometheus-stack
  - metrics-server
  - fluentbit
  - grafana
  - argo-rollouts
  - argocd-extensions
