apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    name: keda
spec:
  project: system
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: "2.8.2"
    chart: keda
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
