apiVersion: v1
kind: Service
metadata:
  labels:
    app: cpe-server
  name: rollout-bluegreen-active
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollout-bluegreen
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cpe-server
  name: rollout-bluegreen-preview
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollout-bluegreen
  type: ClusterIP
