apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: prometheus
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "15.9.1"
    chart: prometheus
    helm:
      values: |
        server:
          replicaCount: 1
          retention: "1d"
          statefulSet:
            enabled: false
          resources: {}
          service:
            enabled: true
            servicePort: 9090
            type: ClusterIP
          ingress:
            enabled: true
            hosts:
              - prometheus.minikube.cloud
            path: /
            pathType: Prefix
            annotations:
              kubernetes.io/ingress.class: nginx
            extraLabels: {}
            tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
