apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: canary
spec:
  source:
    targetRevision: main
    helm:
      values: |-
        replicaCount: 6
        image:
          tag: 1.21-alpine
        ingress:
          enabled: true
          annotations: {}
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: canary.minikube.cloud
              paths: []
          tls: []
