apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: flask-api
spec:
  source:
    helm:
      values: |-
        image:
          tag: v2-success
        ingress:
          enabled: true
          className: nginx
          annotations: {}
          hosts:
            - host: api.minikube.local
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          interval: 15s
          scrapeTimeout: 14s
          namespace: monitoring
        argoRollout:
          enabled: true
          analysis:
            enabled: true
            startingStep: 2
            templates:
            - templateName: success-rate
            prometheus:
              address: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
            successRate: 95
            query:
              interval: 5m # Should match or be related to `steps.pause`
            metrics: 
              interval: 15s
              failureLimit: 3
          trafficManagement:
            enabled: true
            type: nginx
          steps:
            - setWeight: 25
            - pause:
                duration: 5m
            - setWeight: 50
            - pause:
                duration: 5m
            - setWeight: 75
            - pause:
                duration: 5m
            - setWeight: 100
