apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: flask-api
spec:
  source:
    repoURL: https://github.com/luismiguelsaez/helm-charts
    targetRevision: main
    helm:
      values:
        image:
          tag: v2-success
        ingress:
          enabled: true
          className: nginx
          annotations: {}
          hosts:
            - host: api.minikube.local
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        serviceMonitor:
          enabled: true
          interval: 15s
          scrapeTimeout: 14s
          namespace: monitoring
        argoRollout:
          enabled: true
          trafficManagement:
            enabled: true
            type: nginx
          steps:
            - setWeight: 5
            - pause: {}
