apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: flask-api
spec:
  project: examples
  source:
    repoURL: https://github.com/luismiguelsaez/helm-charts
    targetRevision: main
    path: flask-api
    helm:
      values: ""