apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: flask-api
spec:
  source:
    helm:
      values: |-
        image:
          tag: v2
        ingress:
          enabled: true
          className: nginx
          annotations: {}
          hosts:
            - host: api.minikube.local
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          interval: 15s
          scrapeTimeout: 14s
          namespace: monitoring
        argoRollout:
          enabled: true
          tester:
            enabled: true
          analysis:
            enabled: false
            startingStep: 2
            templates:
            - templateName: success-rate
            prometheus:
              address: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
            successRate: "50"
            query:
              interval: 1m
            metrics: 
              interval: 1m
              failureLimit: "5"
          trafficManagement:
            enabled: true
            type: nginx
          steps:
            - setWeight: 25
            - pause:
                duration: 5m
            - analysis:
              templates:
              - templateName: success-rate
              args:
                - name: query-service-name
                  value: flask-api-canary"
                - name: query-interval
                  value: 5m
                - name: prometheus-address
                  value: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
                - name: metrics-interval
                  value: 1m
                - name: metrics-failure-limit
                  value: "5"
                - name: success-rate
                  value: "85"
            - setWeight: 50
            - pause:
                duration: 5m
            - setWeight: 75
            - pause:
                duration: 5m
            - setWeight: 100
          notifications:
            enabled: true
            telegram:
              enabled: true
              user: ""
              token: ""
