apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: fluentbit
spec:
  source:
    helm:
      values: |-
        service:
          type: ClusterIP
          port: 2020
          labels: {}
        serviceMonitor:
          enabled: false
          namespace: monitoring
          interval: 15s
          scrapeTimeout: 10s
          jobLabel: fluentbit
        flush: 1
        logLevel: info
        metricsPort: 2020
        config:
          service: |
            [SERVICE]
            Daemon Off
              Flush {{ .Values.flush }}
              Log_Level {{ .Values.logLevel }}
              Parsers_File parsers.conf
              Parsers_File custom_parsers.conf
              HTTP_Server On
              HTTP_Listen 0.0.0.0
              HTTP_Port {{ .Values.metricsPort }}
              Health_Check On
          inputs: |
            [INPUT]
              Name tail
              Path /var/log/containers/*.log
              multiline.parser docker, cri
              Tag kube.*
              Mem_Buf_Limit 5MB
              Skip_Long_Lines On
          filters: |
            [FILTER]
              Name kubernetes
              Match kube.*
              Merge_Log On
              Keep_Log Off
              K8S-Logging.Parser On
              K8S-Logging.Exclude On
          outputs: |
            [OUTPUT]
              Name stdout
              Match kube.*
          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
          extrafiles: {}
