apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.29.5"
    chart: grafana
    helm:
      values: |-
        adminUser: admin
        adminPassword: strongpassword
        ingress:
          enabled: true
          labels: {}
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - grafana.minikube.cloud
          path: /
          tls: []
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local:9090
              access: proxy
              isDefault: true
