apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/metrics-server
#- ../../infra/apps/elasticsearch
#- ../../infra/apps/vault
- ../../infra/apps/kube-prometheus-stack-crds
#- ../../infra/apps/kyverno
#- ../../infra/apps/kyverno-policies
- ../../infra/apps/gatekeeper
- ../../infra/apps/gatekeeper-policies
#- ../../infra/apps/kube-prometheus-stack
#- ../../infra/apps/argo-rollouts
patchesStrategicMerge:
- ./overrides/metrics-server.yaml
#- ./overrides/vault.yaml
#- ./overrides/fluentbit.yaml
#- ./overrides/grafana.yaml
#- ./overrides/argo-rollouts.yaml
#- ./overrides/kube-prometheus-stack.yaml
#- ./overrides/kyverno.yaml
#- ./overrides/kyverno-policies.yaml
- ./overrides/gatekeeper.yaml
