apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/metrics-server
#- ../../infra/apps/vault
- ../../infra/apps/kube-prometheus-stack-crds
- ../../infra/apps/kube-prometheus-stack
- ../../infra/apps/argo-rollouts
patchesStrategicMerge:
- metrics-server.yaml
#- vault.yaml
#- fluentbit.yaml
#- grafana.yaml
- argo-rollouts.yaml
#- bluegreen-values.yaml
#- canary-values.yaml
#- kube-prometheus-stack.yaml
#- flask-api-values.yaml
