apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/metrics-server
- ../../infra/apps/keda
#- ../../infra/apps/kube-prometheus
#- ../../infra/apps/kube-prometheus/crds.yaml
#- ../../infra/apps/kube-prometheus/stack.yaml
#- ../../infra/apps/kyverno
#- ../../infra/apps/gatekeeper
#- ../../infra/apps/argo-rollouts
#- ../../infra/apps/elasticsearch
#- ../../infra/apps/vault
- ../../services/projects
- ../../services/examples/kustomize-nginx
patchesStrategicMerge:
- ./overrides/metrics-server.yaml
#- ./overrides/vault.yaml
#- ./overrides/fluentbit.yaml
#- ./overrides/grafana.yaml
#- ./overrides/argo-rollouts.yaml
#- ./overrides/kube-prometheus-stack.yaml
#- ./overrides/kyverno.yaml
#- ./overrides/kyverno-policies.yaml
#- ./overrides/gatekeeper.yaml
