apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra
- ../../services
patchesStrategicMerge:
- metrics-server.yaml
- fluentbit.yaml
- grafana.yaml
- argo-rollouts.yaml
- bluegreen-values.yaml
- canary-values.yaml
- prometheus-stack.yaml