apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/metrics-server
#- ../../infra/apps/elasticsearch
#- ../../infra/apps/vault
- ../../infra/apps/kube-prometheus-stack-crds
- ../../infra/apps/kyverno
- ../../infra/apps/kyverno-policies
#- ../../infra/apps/kube-prometheus-stack
#- ../../infra/apps/argo-rollouts
patchesStrategicMerge:
- ./overrides/metrics-server.yaml
#- vault.yaml
#- fluentbit.yaml
#- grafana.yaml
#- ./overrides/argo-rollouts.yaml
#- bluegreen-values.yaml
#- canary-values.yaml
#- ./overrides/kube-prometheus-stack.yaml
#- flask-api-values.yaml
- ./overrides/kyverno.yaml
- ./overrides/kyverno-policies.yaml
