apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../infra/projects
- ../../infra/apps/metrics-server
patchesStrategicMerge:
- metrics-server.yaml
#- fluentbit.yaml
#- grafana.yaml
#- argo-rollouts.yaml
#- bluegreen-values.yaml
#- canary-values.yaml
#- kube-prometheus-stack.yaml
#- flask-api-values.yaml
