apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../infra/projects
bases:
- ../../infra/apps/fluentbit
- ../../infra/apps/metrics-server
patchesStrategicMerge:
- fluentbit.yaml
- metrics-server.yaml