apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: prometheus-stack
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "36.2.0"
    chart: kube-prometheus-stack
    helm:
      skipCrds: false
      values: |-
        prometheusOperator:
          logLevel: info
          serviceMonitor:
            interval: 15s
            scrapeTimeout: 14s
        selfMonitor: true
        prometheus:
          prometheusSpec:
            scrapeInterval: 15s
            scrapeTimeout: 14s
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations: {}
            labels: {}
            hosts:
              - prometheus.minikube.cloud
            pathType: Prefix
            paths:
              - /
            tls: []
        alertmanager:
          alertmanagerSpec:
            logLevel: info
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations: {}
            labels: {}
            hosts:
              - alertmanager.minikube.cloud
            pathType: Prefix
            paths:
              - /
            tls: []
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations: {}
            labels: {}
            hosts:
              - prometheus.minikube.cloud
            pathType: Prefix
            paths:
              - /
            tls: []
