apiService:
  insecureSkipTLSVerify: false
args:
  - --kubelet-insecure-tls
  - --cert-dir=/tmp
  - --secure-port=4443
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
