apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpe-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: cpe-server
    project: cpe
    cluster: main
spec:
  project: cpe
  source:
    repoURL: git@github.com:lokalise/lokalise-custom-processor-server.git
    targetRevision: PLAT-1260_create_k8s_manifests
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cpe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
