apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  releaseName: nginx-ingress
  targetNamespace: ingress
  install:
    createNamespace: true
    remediation:
      retries: 3
  #dependsOn:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      version: "0.13.2"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: nginx-ingress-values
