apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "35.5.1"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
