# https://fluxcd.io/docs/guides/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: ws
  maxHistory: 5
  chart:
    spec:
      chart: nginx
      version: '12.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 4
    service:
      type: ClusterIP
