apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "7.9.3"
    chart: grafana
    helm:
      values: |-
        ingress:
          enabled: true
          labels: {}
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - grafana.minikube.cloud
          path: /
          tls: []
        serviceMonitor:
          enabled: true
          path: /metrics
          labels: {}
          interval: 1m
          scheme: http
          tlsConfig: {}
          scrapeTimeout: 30s
          relabelings: []
        datasources: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
