apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
spec:
  project: monitoring
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "7.9.3"
    chart: grafana
    helm:
      values: |-
        ingress:
          enabled: true
          pathType: ImplementationSpecific
          ingressClassName: ""
          labels: {}
          annotations:
            kubernetes.io/ingress.class: nginx
          hostname: grafana.minikube.cloud
          path: /
          tls:false
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
            namespace: monitoring
            labels: {}
            interval: 1m
            scrapeTimeout: 30s
        datasources:
          secretName: grafana-datasources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
