apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

secretGenerator:
- name: grafana-datasources
  namespace: monitoring
  files:
  - datasources.yaml

vars:
  - name: DS_SECRET
    objref:
      kind: Secret
      apiVersion: v1
      name: grafana-datasources
