apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project containing infrastructure security services

  sourceRepos:
  - '*'
  destinations:
  - namespace: security
    server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  orphanedResources:
    warn: true

  #roles:
  ## A role which provides read-only access to all applications in the project
  #- name: read-only
  #  description: Read-only privileges to my-project
  #  policies:
  #  - p, proj:my-project:read-only, applications, get, my-project/*, allow
  #  groups:
  #  - my-oidc-group
#
  ## A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  ## sync privileges to a CI system
  #- name: ci-role
  #  description: Sync privileges for guestbook-dev
  #  policies:
  #  - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow
#
  #  # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
  #  # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
  #  jwtTokens:
  #  - iat: 1535390316