apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-constraints
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    name: gatekeeper-constraints
spec:
  project: security
  source:
    repoURL: https://github.com/luismiguelsaez/k8s-playground
    targetRevision: master
    path: security/opa/constraints
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
