apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-templates
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: gatekeeper-templates
spec:
  project: security
  source:
    repoURL: https://github.com/open-policy-agent/gatekeeper-library
    targetRevision: master
    path: library
    #kustomize: {}
    #directory:
    #  recurse: false
    #  include:
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
