apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: fluentbit
spec:
  project: monitoring
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "0.20.1"
    chart: fluent-bit
    helm:
      values: |-
        serviceMonitor:
          enabled: true
          namespace: monitoring
          interval: 10s
          scrapeTimeout: 10s
          jobLabel: fluentbit
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
