apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: "3.8.2"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
