apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: aws-load-balancer-controller
spec:
  project: system
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: "1.4.3"
    chart: aws-load-balancer-controller
    helm:
      values: |-
        serviceMonitor:
          enabled: true
          namespace: monitoring
          interval: 10s
          scrapeTimeout: 10s
          jobLabel: fluentbit
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
