apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: vault
spec:
  project: security
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: "0.20.1"
    chart: vault
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
