apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: prometheus-stack
spec:
  source:
    targetRevision: "39.4.0"
    helm:
      values: |-
        fullnameOverride: kube-prom
        prometheusOperator:
          logLevel: info
          serviceMonitor:
            interval: 15s
            scrapeTimeout: 14s
        selfMonitor: true
        prometheus:
          prometheusSpec:
            logLevel: debug
            scrapeInterval: 15s
            scrapeTimeout: 14s
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
            labels: {}
            hosts:
              - prometheus.minikube.cloud
            pathType: Prefix
            paths:
              - /
            tls: []
        alertmanager:
          alertmanagerSpec:
            logLevel: info
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
            labels: {}
            hosts:
              - alertmanager.minikube.cloud
            pathType: Prefix
            paths:
              - /
            tls: []
        grafana:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
            labels: {}
            hosts:
              - grafana.minikube.cloud
            path: /
            tls: []
