apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: kyverno
spec:
  source:
    targetRevision: "v2.5.3"
    helm:
      values: |-
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector: {}
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        serviceMonitor:
          enabled: true
          additionalLabels: 
          scrapeTimeout: 25s
          secure: false
          tlsConfig: {}
        createSelfSignedCert: false
        config:
          resourceFilters:
          - '[Event,*,*]'
          - '[*,kube-system,*]'
          - '[*,kube-public,*]'
          - '[*,kube-node-lease,*]'
          - '[Node,*,*]'
          - '[APIService,*,*]'
          - '[TokenReview,*,*]'
          - '[SubjectAccessReview,*,*]'
          - '[SelfSubjectAccessReview,*,*]'
          - '[Binding,*,*]'
          - '[ReplicaSet,*,*]'
          - '[ReportChangeRequest,*,*]'
          - '[ClusterReportChangeRequest,*,*]'
          # exclude resources from the chart
          - '[ClusterRole,*,{{ template "kyverno.fullname" . }}:*]'
          - '[ClusterRoleBinding,*,{{ template "kyverno.fullname" . }}:*]'
          - '[ServiceAccount,{{ include "kyverno.namespace" . }},{{ template "kyverno.serviceAccountName" . }}]'
          - '[ConfigMap,{{ include "kyverno.namespace" . }},{{ template "kyverno.configMapName" . }}]'
          - '[ConfigMap,{{ include "kyverno.namespace" . }},{{ template "kyverno.metricsConfigMapName" . }}]'
          - '[Deployment,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}]'
          - '[Job,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}-hook-pre-delete]'
          - '[NetworkPolicy,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}]'
          - '[PodDisruptionBudget,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}]'
          - '[Role,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}:*]'
          - '[RoleBinding,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}:*]'
          - '[Secret,{{ include "kyverno.namespace" . }},{{ template "kyverno.serviceName" . }}.{{ template "kyverno.namespace" . }}.svc.*]'
          - '[Service,{{ include "kyverno.namespace" . }},{{ template "kyverno.serviceName" . }}]'
          - '[Service,{{ include "kyverno.namespace" . }},{{ template "kyverno.serviceName" . }}-metrics]'
          - '[ServiceMonitor,{{ if .Values.serviceMonitor.namespace }}{{ .Values.serviceMonitor.namespace }}{{ else }}{{ template "kyverno.namespace" . }}{{ end }},{{ template "kyverno.serviceName" . }}-service-monitor]'
          - '[Pod,{{ include "kyverno.namespace" . }},{{ template "kyverno.fullname" . }}-test]'
