apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: canary
spec:
  project: examples
  source:
    repoURL: https://github.com/luismiguelsaez/helm-charts
    targetRevision: main
    path: argocd-canary
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: examples
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
