apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: fluentbit
spec:
  project: monitoring
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.20.1
    chart: fluent-bit
    helm:
      releaseName: fluent-bit
      version: v2
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
