apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - application.yaml
configMapGenerator:
  - name: fluentbit-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml