apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
spec:
  releaseName: fluentbit
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      version: "0.20.1"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: fluentbit-values
